template:
  path: alb-redirector.yaml
stack_name: agora-prod-alb-redirector
dependencies:
  - prod/agora.yaml
parameters:
  ListenerArn: TBD
  RedirectFromHost: "agora-prod.agora-ampad.org"
  RedirectToHost: "agora.adknowledgeportal.org"
