template:
  path: beanstalk-extras.yaml
stack_name: agora-staging-extras
dependencies:
  - staging/agora.yaml
parameters:
  ListenerArn: TBD
  CertificateArn: !stack_output_external agora-dns::SSLCertificate
