template:
  path: beanstalk.yaml
stack_name: agora-staging
dependencies:
  - staging/agora-common.yaml
  - staging/agora-dns.yaml
  - staging/agora-docdb.yaml
parameters:
  AppDeployBucket: 'org-sagebase-agora-deployment-agora-staging'
  AppEnv: 'staging'
  AppHealthcheckUrl: '/about'
  AutoScalingMaxSize: '4'
  AutoScalingMinSize: '2'
  EbHealthReportingSystem: 'enhanced'
  EbDeploymentPolicy: 'RollingWithAdditionalBatch'
  SnsBounceNotificationEndpoint: 'agora-staging-bounce-notifications@sagebase.org'
  SnsNotificationEndpoint: 'agora-staging@sagebase.org'
  EbSolutionStackName: '64bit Amazon Linux 2 v5.5.0 running Node.js 16'
  EC2InstanceType: 't3.large'
  EC2KeyName: 'agora-access'
  MongodbHost: !stack_output_external agora-docdb-staging::ClusterEndpoint
  MongodbAccessSecurityGroup: !stack_output_external agora-docdb-staging::DocumentDbAccessSecurityGroup
  VpcName: 'agoravpc'
  CertificateArn: !stack_output_external agora-dns::SSLCertificate
