# Provision an EC2 bastian host for agora
template:
  path: bastian.yaml
stack_name: agora-bastian-develop
stack_tags:
  Environment: "develop"
dependencies:
  - agoradev/develop/agora.yaml
  - agoradev/develop/agoravpc.yaml
parameters:
  VpcName: "agoravpc"
  # Name of an the environment either develop, staging or prod
  Environment: "develop"
  # Name of an existing VPC subnet to run the instance in
  VpcSubnet: "PrivateSubnet"
  # Name of an existing EC2 KeyPair to enable SSH access to the instance
  KeyName: "agora-ci"
  # (Optional) ID of the base AMI (supported distros: AWS linux)
  AMIId: ami-055ca5683a7880ef2      # AMI with mongo, synapse and Github hosted runner tools
