template:
  path: beanstalk-extras.yaml
stack_name: agora-develop-extras
stack_tags:
  Environment: "develop"
dependencies:
  - agoradev/develop/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:607346494281:listener/app/awseb-AWSEB-N08JADX0RT38/96cce8aaafaf091a/d737981cbd867081"
  CertificateArn: !stack_output_external agora-dns::SSLCertificate
