# Provision an EC2 bastian host for agora
template:
  path: bastian.yaml
stack_name: agora-bastian-develop
stack_tags:
  Environment: "develop"
dependencies:
  - agoraprod/develop/agora.yaml
  - agoradev/develop/agoravpc.yaml
parameters:
  VpcName: "agoravpc"
  # Name of an the environment either develop, staging or prod
  Environment: "develop"
  # Name of an existing VPC subnet to run the instance in
  VpcSubnet: "PublicSubnet"
  # Name of an existing EC2 KeyPair to enable SSH access to the instance
  KeyName: "agora-ci"
  # (Optional) ID of the base AMI (supported distros: AWS linux)
  AMIId: ami-05b72d008a5718961     # AMI with mongo and synapse tools
