template:
  path: alb-redirector.yaml
stack_name: agora-dev-alb-redirector
dependencies:
  - develop/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:607346494281:listener/app/awseb-AWSEB-N08JADX0RT38/96cce8aaafaf091a/d737981cbd867081"
  RedirectFromHost: "agora-develop.ampadportal.org"
  RedirectToHost: "agora-develop.adknowledgeportal.org"
