template:
  path: documentdb.yaml
stack_name: agora-docdb-staging
stack_tags:
  Environment: "staging"
dependencies:
  - agoraprod/staging/agoravpc.yaml
parameters:
  VpcName: "agoravpc-staging"
  MasterUser: "master"
  MasterPassword: !ssm /agora-staging/MongodbPassword
  DBInstanceClass: "db.r5.large"
