template:
  path: beanstalk-extras.yaml
stack_name: agora-staging-extras
stack_tags:
  Environment: "staging"
dependencies:
  - agoraprod/staging/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:681175625864:listener/app/awseb-AWSEB-1MX73G52E197J/6a35dd0e68395915/cc55a1c45b1a4da4"
  CertificateArn: !stack_output_external agora-dns::SSLCertificate
