template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.8/VPC/vpc-mini.yaml
stack_name: agoravpc
parameters:
  VpcSubnetPrefix: "10.255.45"
  VpcName: "agoravpc"
