template:
  path: alb-redirector.yaml
stack_name: agora-develop-alb-redirector
dependencies:
  - develop/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:681175625864:listener/app/awseb-AWSEB-3772DYG5GR26/9dd56b0dd249d9aa/f83ba5fd6daebc75"
  RedirectFromHost: "agora-develop.agora-ampad.org"
  RedirectToHost: "agora-develop.adknowledgeportal.org"
