# This creates and configures resources for Elastic Beanstalk.
# This template is used to setup extra things after deploying beanstalk apps
AWSTemplateFormatVersion: 2010-09-09
Description: Beanstalk ELB resources and configs
Parameters:
  ListenerArn:
    Description: ARN of the ELB listern
    Type: String
  CertificateArn:
    Description: ARN of the SSL Certificate
    Type: String
Resources:
  # Cloudforamtion does not support adding multiple certificats in Beanstalk
  # with aws:elbv2:listener:443 -> SSLCertificateArns therefore we configure
  # the Beanstalk ELB with a CFN resource in a separate step
  SSLCertificate:
    Type: "AWS::ElasticLoadBalancingV2::ListenerCertificate"
    Properties:
      ListenerArn: !Ref ListenerArn
      Certificates:
        - CertificateArn: !Ref CertificateArn
