Description: Elastic Beanstalk for Agora
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AppDeployBucket:
    Description: Bucket where beanstalk deploys apps from
    Type: String
  AppEnv:
    Type: String
    Description: The application environment
  AppHealthcheckUrl:
    Type: String
    Description: The AWS EB health check path
  AutoScalingMaxSize:
    Type: String
    Default: '2'
  AutoScalingMinSize:
    Type: String
    Default: '1'
  DisableOpencollective:
    Type: String
    Default: true
    Description: 'Disable donation request by Open Collective'
    AllowedValues:
      - true
      - false
    ConstraintDescription: 'Valid values are true or false'
  SnsBounceNotificationEndpoint:
    Type: String
    Description: Email address for SNS bounce notifications
  SnsNotificationEndpoint:
    Type: String
    Description: Email address for AWS SNS notifications
  EbSolutionStackName:
    Description: The AWS Solution Stack
    Type: String
  EC2InstanceType:
    Type: String
    Description: Instance type to use for Elastic Beanstalk Instances
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
  EC2KeyName:
    Description: An existing EC2 keypair to allow secure access to instances
    Type: String
  MongodbHost:
    Type: String
    Description: Mongo database host address
  MongodbPort:
    Type: String
    Description: Mongo database port
    Default: '27017'
  EbRollingUpdateType:
    Type: String
    Description: Env's auto scaling group rolling update type
    Default: 'Health'
  EbDeploymentPolicy:
    Type: String
    Description: Application version deployment type
    Default: 'Rolling'
  MongodbAccessSecurityGroup:
    Type: String
    Description: Security group with access to MongoDB servers
  VpcName:
    Description: Name of an existing VPC to run the instance in.
    Type: String
  CertificateArn:
    Description: ARN of the SSL Certificate
    Type: String
  EnhancedHealthRulesConfigDocument:
    Description: Configuration enhanced health rules (https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced-rules.html#health-enhanced-rules.configdocument)
    Type: String
Resources:
  S3AppDeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref AppDeployBucket
  LoadBalancerAccessLogsBucket:
    Type: 'AWS::S3::Bucket'
  LoadBalancerAccessLogsBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref LoadBalancerAccessLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ModAccess
            Action:
              - 's3:PutObject'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !GetAtt LoadBalancerAccessLogsBucket.Arn
                  - '/*'
            Principal:
              AWS:
                - 127311923021
  S3ManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ListAccess
            Action:
              - 's3:ListBucket'
              - 's3:GetBucketLocation'
            Effect: Allow
            Resource: !GetAtt S3AppDeployBucket.Arn
          - Sid: ModAccess
            Action:
              - 's3:PutObject'
              - 's3:PutObjectAcl'
              - 's3:GetObject'
              - 's3:GetObjectAcl'
              - 's3:DeleteObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - !GetAtt S3AppDeployBucket.Arn
                - '/*'
  # KMS Keys
  KmsDecryptManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ReadAccess
            Action:
              - 'kms:ListKeys'
              - 'kms:ListAliases'
              - 'kms:DescribeKey'
              - 'kms:ListKeyPolicies'
              - 'kms:GetKeyPolicy'
              - 'kms:GetKeyRotationStatus'
              - 'iam:ListUsers'
              - 'iam:ListRoles'
            Effect: Allow
            Resource:
              'Fn::ImportValue': !Sub ${AWS::Region}-agora-common-KmsKeyArn
          - Sid: DecryptAccess
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
            Effect: Allow
            Resource:
              'Fn::ImportValue': !Sub ${AWS::Region}-agora-common-KmsKeyArn
  SsmManagedPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: GetParamAccess
            Action:
              - 'ssm:*'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:ssm:'
                - !Ref AWS::Region
                - ':'
                - !Ref AWS::AccountId
                - ':'
                - 'parameter/'
                - !Ref AWS::StackName
                - '/*'
  BeanstalkConfigTemplate:
    Type: 'AWS::ElasticBeanstalk::ConfigurationTemplate'
    Properties:
      ApplicationName:
        'Fn::ImportValue': !Sub ${AWS::Region}-agora-common-BeanstalkAppName
      SolutionStackName: !Ref EbSolutionStackName
      OptionSettings:
        # EB environment options
        - Namespace: 'aws:ec2:vpc'
          OptionName: VPCId
          Value:
            'Fn::ImportValue': !Sub ${AWS::Region}-${VpcName}-VPCId
        - Namespace: 'aws:ec2:vpc'
          OptionName: ELBScheme
          Value: 'public'
        - Namespace: 'aws:ec2:vpc'
          OptionName: AssociatePublicIpAddress
          Value: 'false'
        - Namespace: 'aws:ec2:vpc'
          OptionName: Subnets
          Value: !Join
            - ','
            - - 'Fn::ImportValue': !Sub ${AWS::Region}-${VpcName}-PrivateSubnet
              - 'Fn::ImportValue': !Sub ${AWS::Region}-${VpcName}-PrivateSubnet1
              - 'Fn::ImportValue': !Sub ${AWS::Region}-${VpcName}-PrivateSubnet2
        - Namespace: 'aws:ec2:vpc'
          OptionName: ELBSubnets
          Value: !Join
            - ','
            - - 'Fn::ImportValue': !Sub ${AWS::Region}-${VpcName}-PublicSubnet
              - 'Fn::ImportValue': !Sub ${AWS::Region}-${VpcName}-PublicSubnet1
              - 'Fn::ImportValue': !Sub ${AWS::Region}-${VpcName}-PublicSubnet2
        - Namespace: 'aws:autoscaling:asg'
          OptionName: MaxSize
          Value: !Ref AutoScalingMaxSize
        - Namespace: 'aws:autoscaling:asg'
          OptionName: MinSize
          Value: !Ref AutoScalingMinSize
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: InstanceType
          Value: !Ref EC2InstanceType
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: EC2KeyName
          Value: !Ref EC2KeyName
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: SecurityGroups
          Value: !Ref MongodbAccessSecurityGroup
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: RootVolumeSize
          Value: '32'
        - Namespace: 'aws:autoscaling:updatepolicy:rollingupdate'
          OptionName: RollingUpdateEnabled
          Value: 'true'
        - Namespace: 'aws:autoscaling:updatepolicy:rollingupdate'
          OptionName: RollingUpdateType
          Value: !Ref EbRollingUpdateType
        - Namespace: 'aws:elasticbeanstalk:application'
          OptionName: Application Healthcheck URL
          Value: !Ref AppHealthcheckUrl
        - Namespace: 'aws:elasticbeanstalk:cloudwatch:logs'
          OptionName: StreamLogs
          Value: 'true'
        - Namespace: 'aws:elasticbeanstalk:cloudwatch:logs'
          OptionName: DeleteOnTerminate
          Value: 'true'
        - Namespace: 'aws:elasticbeanstalk:cloudwatch:logs'
          OptionName: RetentionInDays
          Value: '90'
        - Namespace: 'aws:elasticbeanstalk:command'
          OptionName: DeploymentPolicy
          Value: !Ref EbDeploymentPolicy
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: ServiceRole
          Value:
            'Fn::ImportValue': !Sub ${AWS::Region}-agora-common-BeanstalkServiceRole
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: LoadBalancerType
          Value: 'application'
        - Namespace: 'aws:elbv2:loadbalancer'
          OptionName: AccessLogsS3Bucket
          Value: !Ref LoadBalancerAccessLogsBucket
        - Namespace: 'aws:elbv2:loadbalancer'
          OptionName: AccessLogsS3Enabled
          Value: 'true'
        - Namespace: 'aws:elbv2:listener:443'
          OptionName: SSLCertificateArns
          Value: !Ref CertificateArn
        - Namespace: 'aws:elbv2:listener:443'
          OptionName: Protocol
          Value: HTTPS
        # ELB cipher and TLS protocol versions
        - Namespace: 'aws:elbv2:listener:443'
          OptionName: SSLPolicy
          Value: ELBSecurityPolicy-TLS-1-2-2017-01
        - Namespace: 'aws:elasticbeanstalk:environment:process:default'
          OptionName: Protocol
          Value: 'HTTP'
        - Namespace: 'aws:elasticbeanstalk:healthreporting:system'
          OptionName: SystemType
          Value: 'enhanced'
        - Namespace: 'aws:elasticbeanstalk:healthreporting:system'
          OptionName: ConfigDocument
          Value: !Ref EnhancedHealthRulesConfigDocument
        - Namespace: 'aws:elasticbeanstalk:hostmanager'
          OptionName: LogPublicationControl
          Value: 'true'
        - Namespace: 'aws:elasticbeanstalk:xray'
          OptionName: XRayEnabled
          Value: 'false'
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: MONGODB_HOST
          Value: !Ref MongodbHost
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: MONGODB_PORT
          Value: !Ref MongodbPort
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: APP_ENV
          Value: !Ref AppEnv
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: DISABLE_OPENCOLLECTIVE
          Value: !Ref DisableOpencollective
        # ELB solution stack scheduled updates
        - Namespace: 'aws:elasticbeanstalk:managedactions'
          OptionName: ManagedActionsEnabled
          Value: true
        - Namespace: 'aws:elasticbeanstalk:managedactions'
          OptionName: PreferredStartTime
          Value: Sun:21:00
        - Namespace: 'aws:elasticbeanstalk:managedactions:platformupdate'
          OptionName: UpdateLevel
          Value: minor
        - Namespace: 'aws:elasticbeanstalk:managedactions:platformupdate'
          OptionName: InstanceRefreshEnabled
          Value: false
  BeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName:
        'Fn::ImportValue': !Sub ${AWS::Region}-agora-common-BeanstalkAppName
      TemplateName: !Ref BeanstalkConfigTemplate
      EnvironmentName: !Join
        - '-'
        - - !Ref 'AWS::StackName'
      Tier:
        Name: WebServer
        Type: Standard
  EC2ServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier'
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSESFullAccess'
        - !Ref SsmManagedPolicy
        - !Ref S3ManagedPolicy
        - !Ref KmsDecryptManagedPolicy
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref EC2ServiceRole
  SNSBounceTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint: !Ref SnsBounceNotificationEndpoint
          Protocol: "email"
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint: !Ref SnsNotificationEndpoint
          Protocol: "email"
Outputs:
  S3AppDeployBucket:
    Value: !Ref S3AppDeployBucket
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AppDeployBucket'
  BeanstalkEnvironmentName:
    Value: !Ref BeanstalkEnvironment
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BeanstalkEnvironmentName'
  BeanstalkEnvironmentUrl:
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - BeanstalkEnvironment
          - EndpointURL
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BeanstalkEnvironmentUrl'
  InstanceProfile:
    Value: !Ref InstanceProfile
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-InstanceProfile'
