Description: Setup a Certificate for a domain
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DnsDomainName:
    Description: A fully qualified domain name (i.e. sagebionetworks.org)
    Type: String
Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join
        - '.'
        - - '*'
          - !Ref DnsDomainName
      ValidationMethod: "DNS"
      DomainValidationOptions:
        - DomainName: !Join
            - '.'
            - - '*'
              - !Ref DnsDomainName
          ValidationDomain: !Ref DnsDomainName
Outputs:
  SSLCertificate:
    Value: !Ref SSLCertificate
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SSLCertificate'
  DnsDomainName:
    Value: !Ref DnsDomainName
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-DnsDomainName'
