template:
  path: documentdb.yaml
stack_name: agora-docdb-prod
stack_tags:
  Environment: "prod"
dependencies:
  - agoraprod/prod/agoravpc.yaml
parameters:
  VpcName: "agoravpc-prod"
  MasterUser: "master"
  MasterPassword: !ssm /agora-prod/MongodbPassword
  DBInstanceClass: "db.r5.large"
